from __future__ import annotations

# Performance SLOs (PRD v4)
API_P50_MS = 200
API_P99_MS = 500
WEBSOCKET_LATENCY_MS = 100
DB_QUERY_MS = 50
CACHE_HIT_RATIO_TARGET = 0.90

# Business Targets
DEFLECTION_RATE_TARGET = 0.85
CSAT_TARGET = 4.5

# Security Defaults
PASSWORD_MIN_LENGTH = 12
TOKEN_MAX_SIZE = 8192

# Context Limits
MAX_MESSAGE_LENGTH = 5000
MAX_ATTACHMENT_SIZE_MB = 10
CONTEXT_STACK_DEPTH = 5
